- job:
    name: mistral-docker-buildimage
    parent: publish-openstack-artifacts
    run: playbooks/docker-buildimage/run.yaml
    post-run: playbooks/docker-buildimage/post.yaml
    timeout: 1800
    required-projects:
      - openstack/mistral

- job:
    name: mistral-docker-buildimage-test
    run: playbooks/docker-buildimage/run.yaml
    post-run: playbooks/docker-buildimage/post.yaml
    timeout: 1800
    required-projects:
      - openstack/mistral

- job:
    name: mistral-tox-unit-mysql
    parent: openstack-tox
    vars:
      tox_envlist: unit-mysql
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    timeout: 3600
    required-projects:
      - openstack/mistral-lib
      - openstack/mistral-extra

- job:
    name: mistral-tox-unit-postgresql
    parent: openstack-tox
    vars:
      tox_envlist: unit-postgresql
      tox_environment: {CI_PROJECT: "{{ zuul['project']['name'] }}"}
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
    timeout: 3600
    required-projects:
      - openstack/mistral-lib
      - openstack/mistral-extra

- project:
    templates:
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-cover:
            voting: false
            irrelevant-files:
              - ^.zuul.yaml$
              - ^.*\.rst$
              - ^doc/.*$
              - ^releasenotes/.*$
        - mistral-devstack:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
        - mistral-devstack-tempest-ipv6-only:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
        - mistral-devstack-non-apache-tempest-ipv6-only:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
        - mistral-devstack-non-apache:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
        - mistral-devstack-kombu:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
    queue: mistral
    gate:
      jobs:
        - mistral-devstack:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
        - mistral-devstack-tempest-ipv6-only:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
        - mistral-devstack-non-apache-tempest-ipv6-only:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
        - mistral-devstack-non-apache:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
        - mistral-devstack-kombu:
            required-projects:
              - name: opendev.org/openstack/mistral-tempest-plugin
                override-checkout: 2024.1-last
    post:
      jobs:
        - mistral-docker-buildimage:
            branches: master
    experimental:
      jobs:
        - mistral-tox-unit-mysql
        - mistral-tox-unit-postgresql
        - mistral-docker-buildimage-test:
            branches: master
