{{- $mistralEnabled := .Values.mistral.ingress.enabled -}}
{{- $isK8s := eq (.Values.PAAS_PLATFORM | default "KUBERNETES") "KUBERNETES" -}}
{{- $isHTTProute := .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1" -}}
{{- $tlsRequired :=  .Values.mistral.tls.enabled -}}
{{- if and $mistralEnabled ($isK8s) ($isHTTProute) (not $tlsRequired) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mistral
  labels:
    app: mistral
spec:
  parentRefs:
    - name: {{ .Values.GatewayAPI.gatewayName }}
      namespace: {{ .Values.GatewayAPI.gatewayNamespace }}

  hostnames:
    - {{ include "mistral.ingressHost" . | quote }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mistral
          port: 8989
{{- end }}
---
{{- if and $mistralEnabled ($isK8s) ($isHTTProute) ($tlsRequired) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mistral-redirect
  labels:
    app: mistral
spec:
  parentRefs:
    - name: {{ .Values.GatewayAPI.gatewayName }}
      namespace: {{ .Values.GatewayAPI.gatewayNamespace }}
      port: 80

  hostnames:
    - {{ include "mistral.ingressHost" . | quote }}

  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
{{- end }}
