{{- if and .Values.mistral.ingress.enabled (.Values.mistral.tls.enabled) (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1alpha3")  (eq (.Values.PAAS_PLATFORM | default "KUBERNETES") "KUBERNETES") -}}
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: TLSRoute
metadata:
  name: mistral
  labels:
     app: mistral
spec:
  hostnames:
    - {{ include "mistral.ingressHost" . | quote }}
  parentRefs:
    - name: {{ default .Values.GatewayAPI.gatewayName (include "mistral.gatewayApiName" .)}}
      namespace: {{ default .Values.GatewayAPI.gatewayNamespace (include "mistral.gatewayApiNamespace" .) }}
  rules:
    - backendRefs:
        - name: mistral
          port: 8989
{{ end }}
