---
name: Profanity filter

on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited, reopened]
  pull_request:
    types: [opened, edited, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  apply-filter:
    name: "Apply Profanity Filter"
    runs-on: ubuntu-latest
    steps:
    - name: Scan issue or pull request for profanity
      # Conditionally run the step if the actor isn't a bot
      if: ${{ github.event.sender.type != 'Bot' }}
      uses: IEvangelist/profanity-filter@96fb7c017b3219ea65c6a7ca70e5aed3ce5b4d7d # v13.4.6.2
      id: profanity-filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # See https://bit.ly/potty-mouth-replacement-strategies
        replacement-strategy: middle-asterisk # See Replacement strategy
        custom-profane-words-url: https://github.com/Hesham-Elbadawi/list-of-banned-words/raw/refs/heads/master/ru
        exclude-profane-words: mongo,robot
